### PR TITLE
[MW-511] Publish metronome-logging to be used by Midnight wallet backend

### PR DESCRIPTION
**Pull request by enriquerodbe**
The classes in `metronome-logging` are useful for the wallet backend to implement logging by using contravariant tracers.
This PR should publish `metronome-logging` in our internal repo.

### CODE REVIEW

**Review by biandratti — APPROVED** [review]
Just a minor comment, could you add your name to the list of developers in build.sc?

         mm
      /^(  )^\
      \,(..),/
        V~~V 
        
LGTM!

**Review by aakoshh — APPROVED** [review]
Yay! Agreed, please add yourself to the devs, and any future changes and improvements are very welcome :partying_face:

**Comment by aakoshh** [comment]
@enriquerodbe this is now published https://oss.sonatype.org/#nexus-search;quick~metronome-logging

**Comment by enriquerodbe** [comment]
> @enriquerodbe this is now published https://oss.sonatype.org/#nexus-search;quick~metronome-logging

Awesome!

**Pull request merged**
